// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPNChSCU-5EC3N50qwZCsFo2uT29RcewM',
    appId: '1:435286616809:web:e9a324382ad901a2ad5e78',
    messagingSenderId: '435286616809',
    projectId: 'newrobomaster',
    authDomain: 'newrobomaster.firebaseapp.com',
    storageBucket: 'newrobomaster.appspot.com',
    measurementId: 'G-9NV1743RT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuCbhTEdibJc5dQ61e-7sMKapK81cUCkM',
    appId: '1:435286616809:android:f050c91280c8f1eead5e78',
    messagingSenderId: '435286616809',
    projectId: 'newrobomaster',
    storageBucket: 'newrobomaster.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJFNx5sGi5QtQ8-Z8uLCJYdN41AyaHCwI',
    appId: '1:435286616809:ios:7fea473c118d75f0ad5e78',
    messagingSenderId: '435286616809',
    projectId: 'newrobomaster',
    storageBucket: 'newrobomaster.appspot.com',
    iosBundleId: 'com.example.robomasterNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJFNx5sGi5QtQ8-Z8uLCJYdN41AyaHCwI',
    appId: '1:435286616809:ios:07652ffc32e73f27ad5e78',
    messagingSenderId: '435286616809',
    projectId: 'newrobomaster',
    storageBucket: 'newrobomaster.appspot.com',
    iosBundleId: 'com.example.robomasterNewApp.RunnerTests',
  );
}
